name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    test:
        runs-on: ${{matrix.operating-system}}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ "7.2", "7.3", "7.4" ]
        name: PHP ${{matrix.php }} Unit Test
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: nanasess/setup-php@v3.0.4
              with:
                php-version: ${{ matrix.php }}
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install
            - name: Run Script
              run: vendor/bin/phpunit
    test_lowest:
        runs-on: ${{matrix.operating-system}}
        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php: [ "7.2" ]
        name: PHP ${{matrix.php }} Unit Test Prefer Lowest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: nanasess/setup-php@v3.0.4
              with:
                php-version: ${{ matrix.php }}
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer update --prefer-lowest
            - name: Run Script
              run: vendor/bin/phpunit
    style:
        runs-on: ubuntu-latest
        name: PHP Style Check
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: nanasess/setup-php@v3.0.4
              with:
                php-version: "7.4"
            - name: Install Dependencies
              uses: nick-invision/retry@v1
              with:
                timeout_minutes: 10
                max_attempts: 3
                command: composer install
            - name: Run Script
              run: vendor/bin/phpcs --standard=phpcs-ruleset.xml -p
